### ISSUE TITLE
Code doesn't work as expected

### ISSUE THREAD

**Issue by devildriverz** [SJunWah/lottie-file-optimizer#1]
Don't know why but it converted my 592kb Lottie to 3617kb! 6 times bigger than the original one

[output.json](https://github.com/user-attachments/files/16965132/output.json)
[input.json](https://github.com/user-attachments/files/16965135/input.json)

**Comment by SJunWah** [comment]
Sorry for the late reply. I've been abit busy, that why I cannot respond to you asap. 
However, you can try my optimizer here.
https://tiny-lottie-nextjs.vercel.app/
